name: Run GTests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      run: sudo apt-get install -y cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run Tests
      run: |
        cd build
        ./tests/Tests
